# Generated by Django 5.1.4 on 2024-12-11 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="wein",
            fields=[
                (
                    "drink_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="warehouses.drink",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
            ],
            bases=("warehouses.drink",),
        ),
    ]
